apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: inventory
spec:
  environments:
    - name: single
      build:
        from: main
  components:
    - name: api
      src: "node-js"
      ports:
        - name: http
          port: 8080
      publicPort: http
      